[build]
  base = "/"
  publish = "public"
  command = "gatsby clean && gatsby build"

[build.environment]
  YARN_VERSION = "1.22.17"
  NODE_ENV = "production"

[[plugins]]
  package = "./netlify/plugin"
